#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

# 轻量好用的文件管理器(luci-app-quickfile by sbwml)
name: Build 24.10 quickfile

on:
  schedule:
    - cron: "4 22 * * *"  # 北京时间早上 6 点 04
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Fetch latest prerelease info
        id: fetch_release
        run: |
          curl -s https://api.github.com/repos/wkccd/quickfile/releases \
            | jq 'map(select(.prerelease==false)) | sort_by(.published_at) | last' \
            > release.json

      - name: Parse asset download URLs
        id: parse_assets
        run: |
          X86_URL=$(jq -r '.assets[] 
            | select(.name | test("quickfile_.*_x86_64.ipk")) 
            | .browser_download_url' release.json)

          ARM_URL=$(jq -r '.assets[] 
            | select(.name | test("quickfile_.*_aarch64_generic.ipk")) 
            | .browser_download_url' release.json)

          A53_URL=$(jq -r '.assets[] 
            | select(.name | test("quickfile_.*_aarch64_cortex-a53.ipk")) 
            | .browser_download_url' release.json)

          LUCI_MAIN_URL=$(jq -r '.assets[] 
            | select(.name | test("luci-app-quickfile_.*all.ipk")) 
            | .browser_download_url' release.json)

          LUCI_I18N_URL=$(jq -r '.assets[] 
            | select(.name | test("luci-i18n-quickfile-zh-cn_.*all.ipk")) 
            | .browser_download_url' release.json)

          echo "X86_URL=$X86_URL" >> $GITHUB_ENV
          echo "A53_URL=$A53_URL" >> $GITHUB_ENV
          echo "ARM_URL=$ARM_URL" >> $GITHUB_ENV
          echo "LUCI_MAIN_URL=$LUCI_MAIN_URL" >> $GITHUB_ENV
          echo "LUCI_I18N_URL=$LUCI_I18N_URL" >> $GITHUB_ENV

      - name: Download ipk files
        run: |
          mkdir -p x86 arm64 a53
          wget "$X86_URL" -P x86/
          wget "$ARM_URL" -P arm64/
          wget "$A53_URL" -P a53/
          
          wget "$LUCI_MAIN_URL" -P x86/
          wget "$LUCI_MAIN_URL" -P arm64/
          wget "$LUCI_MAIN_URL" -P a53/
          
          wget "$LUCI_I18N_URL" -P x86/
          wget "$LUCI_I18N_URL" -P arm64/
          wget "$LUCI_I18N_URL" -P a53/

          # 从 x86 的 quickfile 文件名提取日期版本号
          file=$(basename "$X86_URL")
          version="${file#*_}"
          version="${version%%-*}"

          echo "VERSION=$version" >> $GITHUB_ENV
          echo "提取到版本号: $VERSION"

      - name: Create install.sh scripts
        run: |
          cat <<EOF > x86/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install bash
          opkg install quickfile_*.ipk
          opkg install luci-app-quickfile_*.ipk
          opkg install luci-i18n-quickfile-zh-cn_*.ipk
          # fix nginx
          uci set nginx.global.uci_enable='true'
          uci del nginx._lan
          uci del nginx._redirect2ssl
          uci add nginx server
          uci rename nginx.@server[0]='_lan'
          uci set nginx._lan.server_name='_lan'
          uci add_list nginx._lan.listen='80 default_server'
          uci add_list nginx._lan.listen='[::]:80 default_server'
          uci add_list nginx._lan.include='conf.d/*.locations'
          uci set nginx._lan.access_log='off; # logd openwrt'
          uci commit nginx
          service nginx restart
          EOF
          chmod +x x86/install.sh
          cp x86/install.sh arm64/install.sh
          cp x86/install.sh a53/install.sh

      - name: Move directories to makeself
        run: |
          mv x86 makeself/
          mv arm64 makeself/
          mv a53 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh x86/ 24_quickfile_${VERSION}_x86_64.run "by github action" ./install.sh
          ./makeself.sh arm64/ 24_quickfile_${VERSION}_aarch64_generic.run "by github action" ./install.sh
          ./makeself.sh a53/ 24_quickfile_${VERSION}_aarch64_cortex-a53.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV


      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
