#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================
name: Build 24.10 Argon

on:
  schedule:
    - cron: "0 22 * * *"  # 北京时间早上 6 点
  workflow_dispatch:


jobs:
  make-run:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 📦 安装 makeself 工具
        run: sudo apt-get update && sudo apt-get install -y makeself curl

      - name: 🚀 下载argon所有ipk
        run: |
          chmod +x shell/argon.sh
          ./shell/argon.sh

      - name: 📋 拷贝 install.sh 到各平台目录
        run: |
          cp shell/install.sh x86_64/install.sh
          cp shell/install.sh aarch64_generic/install.sh
          chmod +x x86_64/install.sh aarch64_generic/install.sh

      - name: 🔍 提取版本号并打包
        id: pack
        run: |
          mkdir -p output

          # 获取版本
          ARGON_IPK=$(ls aarch64_generic/luci-theme-argon_*.ipk | head -n 1)
          VERSION=$(basename "$ARGON_IPK" | sed -n 's/^luci-theme-argon_\([^-]*-[^_]*\)_.*$/\1/p')

          if [ -z "$VERSION" ]; then
            echo "❌ 无法提取版本号"
            exit 1
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # 打包两个平台
          for PLATFORM in x86_64 aarch64_generic; do
            makeself "$PLATFORM" "output/argon-${VERSION}_${PLATFORM}.run" \
              "argon ${PLATFORM} Installer v${VERSION}" ./install.sh
          done

      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: output/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
