#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================


name: Build 24.10 clashoo

on:
  schedule:
    - cron: "3 22 * * *"  # 北京时间早上 6 点 03
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Fetch latest prerelease info
        id: fetch_release
        run: |
          curl -s https://api.github.com/repos/kenzok8/openwrt-clashoo/releases \
            | jq 'map(select(.prerelease==false)) | sort_by(.published_at) | last' \
            > release.json

      - name: Parse asset download URLs
        id: parse_assets
        run: |
          X86_URL=$(jq -r '.assets[] 
            | select(.name | test("clashoo_.*_x86_64.ipk")) 
            | .browser_download_url' release.json)

          ARM_URL=$(jq -r '.assets[] 
            | select(.name | test("clashoo_.*_aarch64_cortex-a53.ipk")) 
            | .browser_download_url' release.json)

          LUCI_MAIN_URL=$(jq -r '.assets[] 
            | select(.name | test("luci-app-clashoo_.*all.ipk")) 
            | .browser_download_url' release.json)

          LUCI_I18N_URL=$(jq -r '.assets[] 
            | select(.name | test("luci-i18n-clashoo-zh-cn_.*all.ipk")) 
            | .browser_download_url' release.json)

          echo "X86_URL=$X86_URL" >> $GITHUB_ENV
          echo "ARM_URL=$ARM_URL" >> $GITHUB_ENV
          echo "LUCI_MAIN_URL=$LUCI_MAIN_URL" >> $GITHUB_ENV
          echo "LUCI_I18N_URL=$LUCI_I18N_URL" >> $GITHUB_ENV

      - name: Download ipk files
        run: |
          mkdir -p x86 arm64
          wget -q "$X86_URL" -P x86/
          wget -q "$ARM_URL" -P arm64/
          
          wget -q "$LUCI_MAIN_URL" -P x86/
          wget -q "$LUCI_MAIN_URL" -P arm64/
          
          wget -q "$LUCI_I18N_URL" -P x86/
          wget -q "$LUCI_I18N_URL" -P arm64/

          # 从 x86 的 clashoo 文件名提取日期版本号
          fname=$(basename "$X86_URL")
          VERSION=$(echo "$fname" | grep -oP '\d{4}\.\d{2}\.\d{2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "提取到版本号: $VERSION"

      - name: Create install.sh scripts
        run: |
          cat <<EOF > x86/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install clashoo_*.ipk
          opkg install luci-app-clashoo_*.ipk
          opkg install luci-i18n-clashoo-zh-cn_*.ipk
          EOF
          chmod +x x86/install.sh
          cp x86/install.sh arm64/install.sh

      - name: Move directories to makeself
        run: |
          mv x86 makeself/
          mv arm64 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh x86/ clashoo_${VERSION}_x86_64.run "by github action" ./install.sh
          ./makeself.sh arm64/ clashoo_${VERSION}_aarch64_a53.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/clashoo_*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV


      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
