#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

name: Build 24.10 MosDNS

on:
  schedule:
    - cron: "2 22 * * *"  # 北京时间早上 6 点02
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Fetch latest release tag from mosdns
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | jq -r '.tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          
      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest mosdns files
        run: |
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | grep -oP '"browser_download_url":\s*".*aarch64_cortex-a53-openwrt-24.10.tar.gz"' | cut -d '"' -f 4)
          curl -LO $(curl -s https://api.github.com/repos/sbwml/luci-app-mosdns/releases/latest | grep -oP '"browser_download_url":\s*".*x86_64-openwrt-24.10.tar.gz"' | cut -d '"' -f 4)
          tar --one-top-level=aarch64_cortex-a53-openwrt-24.10 -xvzf aarch64_cortex-a53-openwrt-24.10.tar.gz
          tar --one-top-level=x86_64-openwrt-24.10 -xvzf x86_64-openwrt-24.10.tar.gz
      - name: Organize files for aarch64_cortex-a53&x86_64
        run: |
          mkdir mosdns_x86_64 mosdns_aarch64_cortex-a53
          cp x86_64-openwrt-24.10/packages_ci/*.ipk mosdns_x86_64/
          cp aarch64_cortex-a53-openwrt-24.10/packages_ci/*.ipk mosdns_aarch64_cortex-a53/
          # 保存当前路径并进入目标目录
          pushd "mosdns_x86_64" >/dev/null || exit 1
          for file in *~*.ipk; do
          [ -e "$file" ] || continue
          # 构造新文件名，去除 ~ 字符
          new_file="$(echo "$file" | tr -d '~')"
          # 如果目标文件名已存在，则提示并跳过
          if [ -e "$new_file" ]; then
          echo "目标文件已存在，跳过: $new_file"
          continue
          fi
          # 重命名文件
          mv "$file" "$new_file"
          echo "已重命名: $file -> $new_file"
          done
          popd >/dev/null
          pushd "mosdns_aarch64_cortex-a53" >/dev/null || exit 1
          for file in *~*.ipk; do
          [ -e "$file" ] || continue
          # 构造新文件名，去除 ~ 字符
          new_file="$(echo "$file" | tr -d '~')"
          # 如果目标文件名已存在，则提示并跳过
          if [ -e "$new_file" ]; then
          echo "目标文件已存在，跳过: $new_file"
          continue
          fi
          # 重命名文件
          mv "$file" "$new_file"
          echo "已重命名: $file -> $new_file"
          done
          popd >/dev/null
          
      - name: Create install.sh scripts
        run: |
          cat <<EOF > mosdns_x86_64/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install *.ipk
          EOF
          chmod +x mosdns_x86_64/install.sh
          cp mosdns_x86_64/install.sh mosdns_aarch64_cortex-a53/install.sh
          
      - name: Move mosdns directories to makeself
        run: |
          mv mosdns_x86_64 makeself/
          mv mosdns_aarch64_cortex-a53 makeself/
      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh mosdns_x86_64/ mosdns_${{ env.LATEST_TAG }}_x86_64.run "by github action" ./install.sh
          ./makeself.sh mosdns_aarch64_cortex-a53/ mosdns_${{ env.LATEST_TAG }}_aarch64_cortex-a53.run "by github action" ./install.sh
          
      - name: Check file sizes
        run: |
          ls -lh makeself/mosdns_*.run
   
      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/mosdns_*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
