#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================


name: Make 24.10 openwrt-daede

on:
  schedule:
    - cron: "5 22 * * *"  # 北京时间早上 6 点 05
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Fetch latest prerelease info
        id: fetch_release
        run: |
          curl -s https://api.github.com/repos/kenzok8/openwrt-daede/releases \
            | jq 'map(select(.prerelease==false)) | sort_by(.published_at) | last' \
            > release.json


      - name: Parse asset download URLs
        id: parse_assets
        run: bash shell/parse_assets.sh
         
      - name: Download ipk files
        run: bash shell/download_ipks.sh

      - name: Create install.sh scripts
        run: |
          cat <<EOF > x86/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install *.ipk
          EOF
          chmod +x x86/install.sh
          cp x86/install.sh arm64/install.sh
          cp x86/install.sh arm64-a53/install.sh

      - name: Move directories to makeself
        run: |
          mv x86 makeself/
          mv arm64 makeself/
          mv arm64-a53 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh x86/ openwrt-daede_${VERSION}_x86_64.run "by github action" ./install.sh
          ./makeself.sh arm64/ openwrt-daede_${VERSION}_aarch64_generic.run "by github action" ./install.sh
          ./makeself.sh arm64-a53/ openwrt-daede_${VERSION}_aarch64_cortex-a53.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/openwrt-daede_*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV


      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
