name: Build 25.12 SSRP RUN

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64_generic
          - aarch64_cortex-a53

    runs-on: ubuntu-latest

    env:
      OPENWRT_VER: openwrt-25.12

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y makeself curl wget

      - name: Prepare
        run: |
          mkdir -p work makeself

          cat > work/install.sh <<'EOF'
          #!/bin/sh
          cd "$(dirname "$0")"
          apk update
          apk add --allow-untrusted ./*.apk
          EOF
          chmod +x work/install.sh

      - name: Download packages
        shell: bash
        run: |
          BASE_URL="https://opkg.cooluc.com/${OPENWRT_VER}/${{ matrix.arch }}"

          download_apk() {
            pkg="$1"
            file=$(curl -fsSL "$BASE_URL/" | grep -oE "${pkg}-[^\"']+\.apk" | head -n1)
            if [ -z "$file" ]; then
              echo "Cannot find $pkg"
              exit 1
            fi
            wget -q --show-progress -P work "$BASE_URL/$file"
          }

          PACKAGES=(
            luci-app-ssr-plus
            luci-i18n-ssr-plus-zh-cn
            shadowsocksr-libev-ssr-check
            shadowsocksr-libev-ssr-local
            shadowsocksr-libev-ssr-nat
            shadowsocksr-libev-ssr-redir
            shadowsocksr-libev-ssr-server
            chinadns-ng
            dns2tcp
            ipt2socks
            lua-neturl
          )

          for p in "${PACKAGES[@]}"; do
            download_apk "$p"
          done

      - name: Build run
        run: |
          makeself --quiet work makeself/25_SSRP_${{ matrix.arch }}.run "SSRP" ./install.sh


      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV

      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
