#=================================================
# https://github.com/wukongdaily/RunFilesBuilder
# Description: Build RunFiles using GitHub Actions
# Lisence: MIT
# Author: wukongdaily
# Blog: wkdaily.cpolar.cn
#=================================================

# 用户可利用此run单独升级最新版xray-core内核
name: Build 24-25 xray core

on:
  schedule:
    - cron: "3 22 * * *"  # 北京时间早上 6 点 03
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      

      - name: Fetch latest release tag from Xray Core
        id: fetch_latest_tag
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/XTLS/Xray-core/releases \
          | jq -r 'sort_by(.published_at) | reverse | map(select(.prerelease==true)) | .[0].tag_name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
          echo "最新版本:$latest_tag"

      - name: Clone makeself repository
        run: git clone https://github.com/megastep/makeself.git

      - name: Download latest xray-core files
        run: |
          mkdir -p x86 x86-pre arm64 arm64-pre

          # 下载xray-core x86
          wget -O x86-pre/Xray-linux-64.zip https://github.com/XTLS/Xray-core/releases/download/${LATEST_TAG}/Xray-linux-64.zip
          unzip -o -q x86-pre/Xray-linux-64.zip -d x86-pre
          cp -f x86-pre/xray x86/xray
          
          # 下载xray-core arm64
          wget -O arm64-pre/Xray-linux-arm64-v8a.zip  https://github.com/XTLS/Xray-core/releases/download/${LATEST_TAG}/Xray-linux-arm64-v8a.zip
          unzip -o -q arm64-pre/Xray-linux-arm64-v8a.zip -d arm64-pre
          cp -f arm64-pre/xray arm64/xray


      - name: Create install.sh scripts
        run: |
          cat <<EOF > x86/install.sh
          #!/bin/sh
          opkg update
          if [ $? -ne 0 ]; then
              echo "update failed。"
              exit 1
          fi
          opkg install xray-core
          chmod +x xray
          cp xray /usr/bin/xray
          echo "Xray core has been updated to ${LATEST_TAG}"
          EOF
          chmod +x x86/install.sh
          cp x86/install.sh arm64/install.sh

      - name: Move directories to makeself
        run: |
          mv x86 makeself/
          mv arm64 makeself/

      - name: Create self-extracting packages
        run: |
          cd makeself
          ./makeself.sh x86/ xray-core_${LATEST_TAG}_x86_64.run "by github action" ./install.sh
          ./makeself.sh arm64/ xray-core_${LATEST_TAG}_aarch64_a53.run "by github action" ./install.sh

      - name: Check file sizes
        run: |
          ls -lh makeself/xray-core_*.run

      - name: Preparing release name
        run: |
          release_name=$(TZ="Asia/Shanghai" date +'%Y-%m-%d %H:%M Build')
          echo "RELEASE_NAME=$release_name" >> $GITHUB_ENV


      - name: Set tag name
        id: vars
        run: |
          TODAY=$(date -u -d '+8 hour' +'%Y-%m-%d')
          echo "tag_name=$TODAY" >> $GITHUB_ENV
          
      - name: Upload run files as release assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.tag_name }}
          name: "Daily Build - ${{ env.tag_name }}"
          files: makeself/*.run
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
             <p align="left">
              <img src="https://img.shields.io/github/downloads/wkccd/CloudRunFilesBuilder/${{ env.tag_name }}/total?style=for-the-badge&label=%E4%BB%8A%E6%97%A5%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&labelColor=blue&color=black"/>
              <a href="https://wkdaily.cpolar.cn/archives/1">
                <img src="https://img.shields.io/badge/可套用国内加速站下载-FC7C0D?logo=github&logoColor=fff&labelColor=000&style=for-the-badge"/>
              </a>
             </p>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
